services:
  reverse-proxy:
    container_name: reverse_proxy
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      # Enable metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entrypoints.metrics.address=:8082"
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.metrics.rule=Host(`danfimov.com`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.metrics.service=prometheus@internal"
      - "traefik.http.services.metrics.loadbalancer.server.port=8082"
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`danfimov.com`) && PathPrefix(`/whoami`)"
  site:
    container_name: site
    image: cr.yandex/crph9f0poag6rukqpuci/danfimov_com:latest
    expose:
      - 80
    command: uv run uvicorn src.main:app --host "0.0.0.0" --port 80
    labels:
      - "traefik.http.routers.site.rule=Host(`danfimov.com`)"
